### ISSUE TITLE
Dtypes for performance and acquisition seem to be swapped

### ISSUE THREAD

**Issue by gshimansky** [fschlimb/scale-out-benchs#1]
From what I see dtypes for performance and acquisition are swapped. There is `"monthly_reporting_period"` field in performance, but its dtype is described in `pd_load_acquisition_csv` and there is `'orig_channel'` in acquisition names, its dtype is present in `pd_load_performance_csv` function.
Does data from https://rapidsai.github.io/demos/datasets/mortgage-data require modifications?

**Comment by fschlimb** [comment]
Interesting. This was a 1:1 port of the original cuda code. That must have been wrong then.

**Comment by fschlimb** [comment]
No, I  was confused.
Apparently I had fixed this locally already and didn't remember...
Pushed the fix and added a HPAT/SDC version (requires a relatively recent version of HPAT/SDC).

**Comment by gshimansky** [comment]
Thank you, code seems to be correct now. BTW original code was deleted from rapidsai repository in this revision, at time of deletion it had correct dtypes https://github.com/rapidsai/notebooks-contrib/blob/fbfc5e482651f91dbf7f8773cf849e7a7e88ce5b/intermediate_notebooks/E2E/mortgage/mortgage_e2e.ipynb
